#!/bin/python3
import sys

sys.path.append('../')

from RF24 import RF24, RF24_PA_LOW, RF24_1MBPS
import common

# from common import SPI
# spi_0 = SPI(10, 9, 11, 8)
# spi_1 = SPI(20, 19, 21, 7)


# Setup for GPIO pins (CE, CSN) on the Raspberry Pi
# CE pin on GPIO17, CSN pin on GPIO0 (using spidev0.0)

radio_send, radio_recv = common.setup_radios()

# Print out the configuration for verification
print("NRF24L01+ configured successfully!")
print(f"PA Level:  {radio_send.getPALevel()}")
print(f"Data Rate: {radio_send.getDataRate()}")
print(f"Channel:   {radio_send.getChannel()}")
print('-------------------------------------')
print("NRF24L01+ configured successfully!")
print(f"PA Level:  {radio_recv.getPALevel()}")
print(f"Data Rate: {radio_recv.getDataRate()}")
print(f"Channel:   {radio_recv.getChannel()}")